/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface ImageVersion {
    url: string;
    resolutionPercentage: bigint;
    fundingThreshold: bigint;
}
export interface WorkSummary {
    id: TextWorkId;
    workType: WorkType;
    title: string;
    randomUnlock: boolean;
    publishedAt: Time;
    author: string;
    targetAmount: bigint;
    contentPreview: string;
    timeWindow: TimeWindow;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface WorkDetail {
    work: Work;
    unlocked: boolean;
    receivedAmount: bigint;
    unlockProgress: bigint;
}
export type TextWorkId = string;
export interface FileVersion {
    url: string;
    originalFilename: string;
    mimeType: string;
    fundingThreshold: bigint;
}
export interface AppSettings {
    analyticsEnabled: boolean;
    gaTrackingId?: string;
    allowAnonymousPublishing: boolean;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Work {
    id: TextWorkId;
    workType: WorkType;
    fileVersion?: FileVersion;
    title: string;
    creator: Principal;
    deleted: boolean;
    progressiveUnlock: boolean;
    content: string;
    accountId: string;
    randomUnlock: boolean;
    publishedAt: Time;
    author: string;
    targetAmount: bigint;
    imageVersions?: Array<ImageVersion>;
    timeWindow: TimeWindow;
}
export interface UserProfile {
    principalAddress?: Principal;
    name: string;
    createdAt: Time;
    updatedAt: Time;
}
export interface RandomUnlockState {
    unlockedString: string;
    lastUpdated: Time;
    fundingPercentageWhenGenerated: bigint;
    viewerPrincipal: Principal;
    workId: TextWorkId;
}
export enum TimeWindow {
    permanent = "permanent",
    last1Hour = "last1Hour",
    last24Hours = "last24Hours",
    last7Days = "last7Days",
    last30Days = "last30Days"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WorkType {
    audio = "audio",
    file = "file",
    text = "text",
    image = "image"
}
export interface backendInterface {
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createWork(id: TextWorkId, title: string, content: string, workType: WorkType, targetAmount: bigint, accountId: string, progressiveUnlock: boolean, randomUnlock: boolean, fileVersion: FileVersion | null, imageVersions: Array<ImageVersion> | null, timeWindow: TimeWindow): Promise<void>;
    deleteWork(id: TextWorkId): Promise<void>;
    getActiveWork(id: TextWorkId): Promise<Work>;
    getActiveWorksByOwner(owner: Principal): Promise<Array<WorkSummary>>;
    getAllPaidWorks(): Promise<Array<WorkSummary>>;
    getAllWorksAdmin(): Promise<Array<Work>>;
    getAnalyticsSettings(): Promise<{
        analyticsEnabled: boolean;
        gaTrackingId?: string;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getRandomUnlockState(workId: TextWorkId): Promise<RandomUnlockState | null>;
    getRandomUnlockStatusLookup(id: TextWorkId): Promise<boolean>;
    getRemovedWorksByOwner(owner: Principal): Promise<Array<WorkSummary>>;
    getSettings(): Promise<AppSettings>;
    getUserPrincipal(): Promise<Principal | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getValidWorksByCreator(creator: Principal): Promise<Array<WorkSummary>>;
    getWork(id: TextWorkId): Promise<Work | null>;
    getWorkDetailsWithTimeWindow(workId: TextWorkId): Promise<WorkDetail>;
    getWorkTimeWindow(workId: TextWorkId): Promise<TimeWindow>;
    getWorksByCreator(creator: Principal): Promise<Array<WorkSummary>>;
    getWorksForCreator(creator: Principal): Promise<Array<WorkSummary>>;
    getWorksWithRandomUnlock(): Promise<Array<WorkSummary>>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveRandomUnlockState(workId: TextWorkId, unlockedText: string, fundingPercentage: bigint): Promise<void>;
    setUserPrincipal(principal: Principal): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAnalyticsSettings(settings: {
        analyticsEnabled: boolean;
        gaTrackingId?: string;
    }): Promise<void>;
    updateRandomUnlockState(workId: TextWorkId, newUnlockedText: string, currentFundingPercentage: bigint): Promise<void>;
    updateSettings(settings: AppSettings): Promise<void>;
    updateWork(id: TextWorkId, title: string, content: string, author: string, workType: WorkType, targetAmount: bigint, accountId: string, progressiveUnlock: boolean, randomUnlock: boolean, fileVersion: FileVersion | null, imageVersions: Array<ImageVersion> | null): Promise<void>;
}
import type { AppSettings as _AppSettings, FileVersion as _FileVersion, ImageVersion as _ImageVersion, RandomUnlockState as _RandomUnlockState, TextWorkId as _TextWorkId, Time as _Time, TimeWindow as _TimeWindow, UserProfile as _UserProfile, UserRole as _UserRole, Work as _Work, WorkDetail as _WorkDetail, WorkSummary as _WorkSummary, WorkType as _WorkType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async createWork(arg0: TextWorkId, arg1: string, arg2: string, arg3: WorkType, arg4: bigint, arg5: string, arg6: boolean, arg7: boolean, arg8: FileVersion | null, arg9: Array<ImageVersion> | null, arg10: TimeWindow): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createWork(arg0, arg1, arg2, to_candid_WorkType_n3(this.uploadFile, this.downloadFile, arg3), arg4, arg5, arg6, arg7, to_candid_opt_n5(this.uploadFile, this.downloadFile, arg8), to_candid_opt_n6(this.uploadFile, this.downloadFile, arg9), to_candid_TimeWindow_n7(this.uploadFile, this.downloadFile, arg10));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWork(arg0, arg1, arg2, to_candid_WorkType_n3(this.uploadFile, this.downloadFile, arg3), arg4, arg5, arg6, arg7, to_candid_opt_n5(this.uploadFile, this.downloadFile, arg8), to_candid_opt_n6(this.uploadFile, this.downloadFile, arg9), to_candid_TimeWindow_n7(this.uploadFile, this.downloadFile, arg10));
            return result;
        }
    }
    async deleteWork(arg0: TextWorkId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWork(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWork(arg0);
            return result;
        }
    }
    async getActiveWork(arg0: TextWorkId): Promise<Work> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveWork(arg0);
                return from_candid_Work_n9(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveWork(arg0);
            return from_candid_Work_n9(this.uploadFile, this.downloadFile, result);
        }
    }
    async getActiveWorksByOwner(arg0: Principal): Promise<Array<WorkSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveWorksByOwner(arg0);
                return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveWorksByOwner(arg0);
            return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllPaidWorks(): Promise<Array<WorkSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPaidWorks();
                return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPaidWorks();
            return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllWorksAdmin(): Promise<Array<Work>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorksAdmin();
                return from_candid_vec_n20(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorksAdmin();
            return from_candid_vec_n20(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAnalyticsSettings(): Promise<{
        analyticsEnabled: boolean;
        gaTrackingId?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsSettings();
                return from_candid_record_n21(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsSettings();
            return from_candid_record_n21(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n23(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n23(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getRandomUnlockState(arg0: TextWorkId): Promise<RandomUnlockState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRandomUnlockState(arg0);
                return from_candid_opt_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRandomUnlockState(arg0);
            return from_candid_opt_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getRandomUnlockStatusLookup(arg0: TextWorkId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getRandomUnlockStatusLookup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRandomUnlockStatusLookup(arg0);
            return result;
        }
    }
    async getRemovedWorksByOwner(arg0: Principal): Promise<Array<WorkSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRemovedWorksByOwner(arg0);
                return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRemovedWorksByOwner(arg0);
            return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async getSettings(): Promise<AppSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_AppSettings_n30(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_AppSettings_n30(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserPrincipal(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPrincipal();
                return from_candid_opt_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPrincipal();
            return from_candid_opt_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n23(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n23(this.uploadFile, this.downloadFile, result);
        }
    }
    async getValidWorksByCreator(arg0: Principal): Promise<Array<WorkSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getValidWorksByCreator(arg0);
                return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getValidWorksByCreator(arg0);
            return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async getWork(arg0: TextWorkId): Promise<Work | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWork(arg0);
                return from_candid_opt_n32(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWork(arg0);
            return from_candid_opt_n32(this.uploadFile, this.downloadFile, result);
        }
    }
    async getWorkDetailsWithTimeWindow(arg0: TextWorkId): Promise<WorkDetail> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkDetailsWithTimeWindow(arg0);
                return from_candid_WorkDetail_n33(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkDetailsWithTimeWindow(arg0);
            return from_candid_WorkDetail_n33(this.uploadFile, this.downloadFile, result);
        }
    }
    async getWorkTimeWindow(arg0: TextWorkId): Promise<TimeWindow> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkTimeWindow(arg0);
                return from_candid_TimeWindow_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkTimeWindow(arg0);
            return from_candid_TimeWindow_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async getWorksByCreator(arg0: Principal): Promise<Array<WorkSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorksByCreator(arg0);
                return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorksByCreator(arg0);
            return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async getWorksForCreator(arg0: Principal): Promise<Array<WorkSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorksForCreator(arg0);
                return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorksForCreator(arg0);
            return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async getWorksWithRandomUnlock(): Promise<Array<WorkSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorksWithRandomUnlock();
                return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorksWithRandomUnlock();
            return from_candid_vec_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n35(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n35(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async saveRandomUnlockState(arg0: TextWorkId, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveRandomUnlockState(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveRandomUnlockState(arg0, arg1, arg2);
            return result;
        }
    }
    async setUserPrincipal(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserPrincipal(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAnalyticsSettings(arg0: {
        analyticsEnabled: boolean;
        gaTrackingId?: string;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnalyticsSettings(to_candid_record_n37(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnalyticsSettings(to_candid_record_n37(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async updateRandomUnlockState(arg0: TextWorkId, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRandomUnlockState(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRandomUnlockState(arg0, arg1, arg2);
            return result;
        }
    }
    async updateSettings(arg0: AppSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(to_candid_AppSettings_n38(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(to_candid_AppSettings_n38(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async updateWork(arg0: TextWorkId, arg1: string, arg2: string, arg3: string, arg4: WorkType, arg5: bigint, arg6: string, arg7: boolean, arg8: boolean, arg9: FileVersion | null, arg10: Array<ImageVersion> | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWork(arg0, arg1, arg2, arg3, to_candid_WorkType_n3(this.uploadFile, this.downloadFile, arg4), arg5, arg6, arg7, arg8, to_candid_opt_n5(this.uploadFile, this.downloadFile, arg9), to_candid_opt_n6(this.uploadFile, this.downloadFile, arg10));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWork(arg0, arg1, arg2, arg3, to_candid_WorkType_n3(this.uploadFile, this.downloadFile, arg4), arg5, arg6, arg7, arg8, to_candid_opt_n5(this.uploadFile, this.downloadFile, arg9), to_candid_opt_n6(this.uploadFile, this.downloadFile, arg10));
            return result;
        }
    }
}
function from_candid_AppSettings_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppSettings): AppSettings {
    return from_candid_record_n31(uploadFile, downloadFile, value);
}
function from_candid_TimeWindow_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimeWindow): TimeWindow {
    return from_candid_variant_n16(uploadFile, downloadFile, value);
}
function from_candid_UserProfile_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n25(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(uploadFile, downloadFile, value);
}
function from_candid_WorkDetail_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkDetail): WorkDetail {
    return from_candid_record_n34(uploadFile, downloadFile, value);
}
function from_candid_WorkSummary_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkSummary): WorkSummary {
    return from_candid_record_n19(uploadFile, downloadFile, value);
}
function from_candid_WorkType_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkType): WorkType {
    return from_candid_variant_n12(uploadFile, downloadFile, value);
}
function from_candid_Work_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Work): Work {
    return from_candid_record_n10(uploadFile, downloadFile, value);
}
function from_candid_opt_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileVersion]): FileVersion | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_ImageVersion>]): Array<ImageVersion> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n24(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RandomUnlockState]): RandomUnlockState | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Work]): Work | null {
    return value.length === 0 ? null : from_candid_Work_n9(uploadFile, downloadFile, value[0]);
}
function from_candid_record_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TextWorkId;
    workType: _WorkType;
    fileVersion: [] | [_FileVersion];
    title: string;
    creator: Principal;
    deleted: boolean;
    progressiveUnlock: boolean;
    content: string;
    accountId: string;
    randomUnlock: boolean;
    publishedAt: _Time;
    author: string;
    targetAmount: bigint;
    imageVersions: [] | [Array<_ImageVersion>];
    timeWindow: _TimeWindow;
}): {
    id: TextWorkId;
    workType: WorkType;
    fileVersion?: FileVersion;
    title: string;
    creator: Principal;
    deleted: boolean;
    progressiveUnlock: boolean;
    content: string;
    accountId: string;
    randomUnlock: boolean;
    publishedAt: Time;
    author: string;
    targetAmount: bigint;
    imageVersions?: Array<ImageVersion>;
    timeWindow: TimeWindow;
} {
    return {
        id: value.id,
        workType: from_candid_WorkType_n11(uploadFile, downloadFile, value.workType),
        fileVersion: record_opt_to_undefined(from_candid_opt_n13(uploadFile, downloadFile, value.fileVersion)),
        title: value.title,
        creator: value.creator,
        deleted: value.deleted,
        progressiveUnlock: value.progressiveUnlock,
        content: value.content,
        accountId: value.accountId,
        randomUnlock: value.randomUnlock,
        publishedAt: value.publishedAt,
        author: value.author,
        targetAmount: value.targetAmount,
        imageVersions: record_opt_to_undefined(from_candid_opt_n14(uploadFile, downloadFile, value.imageVersions)),
        timeWindow: from_candid_TimeWindow_n15(uploadFile, downloadFile, value.timeWindow)
    };
}
function from_candid_record_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TextWorkId;
    workType: _WorkType;
    title: string;
    randomUnlock: boolean;
    publishedAt: _Time;
    author: string;
    targetAmount: bigint;
    contentPreview: string;
    timeWindow: _TimeWindow;
}): {
    id: TextWorkId;
    workType: WorkType;
    title: string;
    randomUnlock: boolean;
    publishedAt: Time;
    author: string;
    targetAmount: bigint;
    contentPreview: string;
    timeWindow: TimeWindow;
} {
    return {
        id: value.id,
        workType: from_candid_WorkType_n11(uploadFile, downloadFile, value.workType),
        title: value.title,
        randomUnlock: value.randomUnlock,
        publishedAt: value.publishedAt,
        author: value.author,
        targetAmount: value.targetAmount,
        contentPreview: value.contentPreview,
        timeWindow: from_candid_TimeWindow_n15(uploadFile, downloadFile, value.timeWindow)
    };
}
function from_candid_record_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    analyticsEnabled: boolean;
    gaTrackingId: [] | [string];
}): {
    analyticsEnabled: boolean;
    gaTrackingId?: string;
} {
    return {
        analyticsEnabled: value.analyticsEnabled,
        gaTrackingId: record_opt_to_undefined(from_candid_opt_n22(uploadFile, downloadFile, value.gaTrackingId))
    };
}
function from_candid_record_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principalAddress: [] | [Principal];
    name: string;
    createdAt: _Time;
    updatedAt: _Time;
}): {
    principalAddress?: Principal;
    name: string;
    createdAt: Time;
    updatedAt: Time;
} {
    return {
        principalAddress: record_opt_to_undefined(from_candid_opt_n26(uploadFile, downloadFile, value.principalAddress)),
        name: value.name,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    analyticsEnabled: boolean;
    gaTrackingId: [] | [string];
    allowAnonymousPublishing: boolean;
}): {
    analyticsEnabled: boolean;
    gaTrackingId?: string;
    allowAnonymousPublishing: boolean;
} {
    return {
        analyticsEnabled: value.analyticsEnabled,
        gaTrackingId: record_opt_to_undefined(from_candid_opt_n22(uploadFile, downloadFile, value.gaTrackingId)),
        allowAnonymousPublishing: value.allowAnonymousPublishing
    };
}
function from_candid_record_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    work: _Work;
    unlocked: boolean;
    receivedAmount: bigint;
    unlockProgress: bigint;
}): {
    work: Work;
    unlocked: boolean;
    receivedAmount: bigint;
    unlockProgress: bigint;
} {
    return {
        work: from_candid_Work_n9(uploadFile, downloadFile, value.work),
        unlocked: value.unlocked,
        receivedAmount: value.receivedAmount,
        unlockProgress: value.unlockProgress
    };
}
function from_candid_variant_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    audio: null;
} | {
    file: null;
} | {
    text: null;
} | {
    image: null;
}): WorkType {
    return "audio" in value ? WorkType.audio : "file" in value ? WorkType.file : "text" in value ? WorkType.text : "image" in value ? WorkType.image : value;
}
function from_candid_variant_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    permanent: null;
} | {
    last1Hour: null;
} | {
    last24Hours: null;
} | {
    last7Days: null;
} | {
    last30Days: null;
}): TimeWindow {
    return "permanent" in value ? TimeWindow.permanent : "last1Hour" in value ? TimeWindow.last1Hour : "last24Hours" in value ? TimeWindow.last24Hours : "last7Days" in value ? TimeWindow.last7Days : "last30Days" in value ? TimeWindow.last30Days : value;
}
function from_candid_variant_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkSummary>): Array<WorkSummary> {
    return value.map((x)=>from_candid_WorkSummary_n18(uploadFile, downloadFile, x));
}
function from_candid_vec_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Work>): Array<Work> {
    return value.map((x)=>from_candid_Work_n9(uploadFile, downloadFile, x));
}
function to_candid_AppSettings_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppSettings): _AppSettings {
    return to_candid_record_n39(uploadFile, downloadFile, value);
}
function to_candid_TimeWindow_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimeWindow): _TimeWindow {
    return to_candid_variant_n8(uploadFile, downloadFile, value);
}
function to_candid_UserProfile_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n36(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(uploadFile, downloadFile, value);
}
function to_candid_WorkType_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkType): _WorkType {
    return to_candid_variant_n4(uploadFile, downloadFile, value);
}
function to_candid_opt_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileVersion | null): [] | [_FileVersion] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ImageVersion> | null): [] | [Array<_ImageVersion>] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principalAddress?: Principal;
    name: string;
    createdAt: Time;
    updatedAt: Time;
}): {
    principalAddress: [] | [Principal];
    name: string;
    createdAt: _Time;
    updatedAt: _Time;
} {
    return {
        principalAddress: value.principalAddress ? candid_some(value.principalAddress) : candid_none(),
        name: value.name,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt
    };
}
function to_candid_record_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    analyticsEnabled: boolean;
    gaTrackingId?: string;
}): {
    analyticsEnabled: boolean;
    gaTrackingId: [] | [string];
} {
    return {
        analyticsEnabled: value.analyticsEnabled,
        gaTrackingId: value.gaTrackingId ? candid_some(value.gaTrackingId) : candid_none()
    };
}
function to_candid_record_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    analyticsEnabled: boolean;
    gaTrackingId?: string;
    allowAnonymousPublishing: boolean;
}): {
    analyticsEnabled: boolean;
    gaTrackingId: [] | [string];
    allowAnonymousPublishing: boolean;
} {
    return {
        analyticsEnabled: value.analyticsEnabled,
        gaTrackingId: value.gaTrackingId ? candid_some(value.gaTrackingId) : candid_none(),
        allowAnonymousPublishing: value.allowAnonymousPublishing
    };
}
function to_candid_variant_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkType): {
    audio: null;
} | {
    file: null;
} | {
    text: null;
} | {
    image: null;
} {
    return value == WorkType.audio ? {
        audio: null
    } : value == WorkType.file ? {
        file: null
    } : value == WorkType.text ? {
        text: null
    } : value == WorkType.image ? {
        image: null
    } : value;
}
function to_candid_variant_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimeWindow): {
    permanent: null;
} | {
    last1Hour: null;
} | {
    last24Hours: null;
} | {
    last7Days: null;
} | {
    last30Days: null;
} {
    return value == TimeWindow.permanent ? {
        permanent: null
    } : value == TimeWindow.last1Hour ? {
        last1Hour: null
    } : value == TimeWindow.last24Hours ? {
        last24Hours: null
    } : value == TimeWindow.last7Days ? {
        last7Days: null
    } : value == TimeWindow.last30Days ? {
        last30Days: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
