/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TextWorkId = IDL.Text;
export const WorkType = IDL.Variant({
  'audio' : IDL.Null,
  'file' : IDL.Null,
  'text' : IDL.Null,
  'image' : IDL.Null,
});
export const FileVersion = IDL.Record({
  'url' : IDL.Text,
  'originalFilename' : IDL.Text,
  'mimeType' : IDL.Text,
  'fundingThreshold' : IDL.Nat,
});
export const ImageVersion = IDL.Record({
  'url' : IDL.Text,
  'resolutionPercentage' : IDL.Nat,
  'fundingThreshold' : IDL.Nat,
});
export const TimeWindow = IDL.Variant({
  'permanent' : IDL.Null,
  'last1Hour' : IDL.Null,
  'last24Hours' : IDL.Null,
  'last7Days' : IDL.Null,
  'last30Days' : IDL.Null,
});
export const Time = IDL.Int;
export const Work = IDL.Record({
  'id' : TextWorkId,
  'workType' : WorkType,
  'fileVersion' : IDL.Opt(FileVersion),
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'deleted' : IDL.Bool,
  'progressiveUnlock' : IDL.Bool,
  'content' : IDL.Text,
  'accountId' : IDL.Text,
  'randomUnlock' : IDL.Bool,
  'publishedAt' : Time,
  'author' : IDL.Text,
  'targetAmount' : IDL.Nat,
  'imageVersions' : IDL.Opt(IDL.Vec(ImageVersion)),
  'timeWindow' : TimeWindow,
});
export const WorkSummary = IDL.Record({
  'id' : TextWorkId,
  'workType' : WorkType,
  'title' : IDL.Text,
  'randomUnlock' : IDL.Bool,
  'publishedAt' : Time,
  'author' : IDL.Text,
  'targetAmount' : IDL.Nat,
  'contentPreview' : IDL.Text,
  'timeWindow' : TimeWindow,
});
export const UserProfile = IDL.Record({
  'principalAddress' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
});
export const RandomUnlockState = IDL.Record({
  'unlockedString' : IDL.Text,
  'lastUpdated' : Time,
  'fundingPercentageWhenGenerated' : IDL.Nat,
  'viewerPrincipal' : IDL.Principal,
  'workId' : TextWorkId,
});
export const AppSettings = IDL.Record({
  'analyticsEnabled' : IDL.Bool,
  'gaTrackingId' : IDL.Opt(IDL.Text),
  'allowAnonymousPublishing' : IDL.Bool,
});
export const WorkDetail = IDL.Record({
  'work' : Work,
  'unlocked' : IDL.Bool,
  'receivedAmount' : IDL.Nat,
  'unlockProgress' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createWork' : IDL.Func(
      [
        TextWorkId,
        IDL.Text,
        IDL.Text,
        WorkType,
        IDL.Nat,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Opt(FileVersion),
        IDL.Opt(IDL.Vec(ImageVersion)),
        TimeWindow,
      ],
      [],
      [],
    ),
  'deleteWork' : IDL.Func([TextWorkId], [], []),
  'getActiveWork' : IDL.Func([TextWorkId], [Work], ['query']),
  'getActiveWorksByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(WorkSummary)],
      ['query'],
    ),
  'getAllPaidWorks' : IDL.Func([], [IDL.Vec(WorkSummary)], ['query']),
  'getAllWorksAdmin' : IDL.Func([], [IDL.Vec(Work)], ['query']),
  'getAnalyticsSettings' : IDL.Func(
      [],
      [
        IDL.Record({
          'analyticsEnabled' : IDL.Bool,
          'gaTrackingId' : IDL.Opt(IDL.Text),
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRandomUnlockState' : IDL.Func(
      [TextWorkId],
      [IDL.Opt(RandomUnlockState)],
      ['query'],
    ),
  'getRandomUnlockStatusLookup' : IDL.Func([TextWorkId], [IDL.Bool], ['query']),
  'getRemovedWorksByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(WorkSummary)],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [AppSettings], ['query']),
  'getUserPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getValidWorksByCreator' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(WorkSummary)],
      ['query'],
    ),
  'getWork' : IDL.Func([TextWorkId], [IDL.Opt(Work)], ['query']),
  'getWorkDetailsWithTimeWindow' : IDL.Func([TextWorkId], [WorkDetail], []),
  'getWorkTimeWindow' : IDL.Func([TextWorkId], [TimeWindow], ['query']),
  'getWorksByCreator' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(WorkSummary)],
      ['query'],
    ),
  'getWorksForCreator' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(WorkSummary)],
      ['query'],
    ),
  'getWorksWithRandomUnlock' : IDL.Func([], [IDL.Vec(WorkSummary)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveRandomUnlockState' : IDL.Func([TextWorkId, IDL.Text, IDL.Nat], [], []),
  'setUserPrincipal' : IDL.Func([IDL.Principal], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAnalyticsSettings' : IDL.Func(
      [
        IDL.Record({
          'analyticsEnabled' : IDL.Bool,
          'gaTrackingId' : IDL.Opt(IDL.Text),
        }),
      ],
      [],
      [],
    ),
  'updateRandomUnlockState' : IDL.Func([TextWorkId, IDL.Text, IDL.Nat], [], []),
  'updateSettings' : IDL.Func([AppSettings], [], []),
  'updateWork' : IDL.Func(
      [
        TextWorkId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        WorkType,
        IDL.Nat,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Opt(FileVersion),
        IDL.Opt(IDL.Vec(ImageVersion)),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TextWorkId = IDL.Text;
  const WorkType = IDL.Variant({
    'audio' : IDL.Null,
    'file' : IDL.Null,
    'text' : IDL.Null,
    'image' : IDL.Null,
  });
  const FileVersion = IDL.Record({
    'url' : IDL.Text,
    'originalFilename' : IDL.Text,
    'mimeType' : IDL.Text,
    'fundingThreshold' : IDL.Nat,
  });
  const ImageVersion = IDL.Record({
    'url' : IDL.Text,
    'resolutionPercentage' : IDL.Nat,
    'fundingThreshold' : IDL.Nat,
  });
  const TimeWindow = IDL.Variant({
    'permanent' : IDL.Null,
    'last1Hour' : IDL.Null,
    'last24Hours' : IDL.Null,
    'last7Days' : IDL.Null,
    'last30Days' : IDL.Null,
  });
  const Time = IDL.Int;
  const Work = IDL.Record({
    'id' : TextWorkId,
    'workType' : WorkType,
    'fileVersion' : IDL.Opt(FileVersion),
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'deleted' : IDL.Bool,
    'progressiveUnlock' : IDL.Bool,
    'content' : IDL.Text,
    'accountId' : IDL.Text,
    'randomUnlock' : IDL.Bool,
    'publishedAt' : Time,
    'author' : IDL.Text,
    'targetAmount' : IDL.Nat,
    'imageVersions' : IDL.Opt(IDL.Vec(ImageVersion)),
    'timeWindow' : TimeWindow,
  });
  const WorkSummary = IDL.Record({
    'id' : TextWorkId,
    'workType' : WorkType,
    'title' : IDL.Text,
    'randomUnlock' : IDL.Bool,
    'publishedAt' : Time,
    'author' : IDL.Text,
    'targetAmount' : IDL.Nat,
    'contentPreview' : IDL.Text,
    'timeWindow' : TimeWindow,
  });
  const UserProfile = IDL.Record({
    'principalAddress' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
  });
  const RandomUnlockState = IDL.Record({
    'unlockedString' : IDL.Text,
    'lastUpdated' : Time,
    'fundingPercentageWhenGenerated' : IDL.Nat,
    'viewerPrincipal' : IDL.Principal,
    'workId' : TextWorkId,
  });
  const AppSettings = IDL.Record({
    'analyticsEnabled' : IDL.Bool,
    'gaTrackingId' : IDL.Opt(IDL.Text),
    'allowAnonymousPublishing' : IDL.Bool,
  });
  const WorkDetail = IDL.Record({
    'work' : Work,
    'unlocked' : IDL.Bool,
    'receivedAmount' : IDL.Nat,
    'unlockProgress' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createWork' : IDL.Func(
        [
          TextWorkId,
          IDL.Text,
          IDL.Text,
          WorkType,
          IDL.Nat,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Opt(FileVersion),
          IDL.Opt(IDL.Vec(ImageVersion)),
          TimeWindow,
        ],
        [],
        [],
      ),
    'deleteWork' : IDL.Func([TextWorkId], [], []),
    'getActiveWork' : IDL.Func([TextWorkId], [Work], ['query']),
    'getActiveWorksByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(WorkSummary)],
        ['query'],
      ),
    'getAllPaidWorks' : IDL.Func([], [IDL.Vec(WorkSummary)], ['query']),
    'getAllWorksAdmin' : IDL.Func([], [IDL.Vec(Work)], ['query']),
    'getAnalyticsSettings' : IDL.Func(
        [],
        [
          IDL.Record({
            'analyticsEnabled' : IDL.Bool,
            'gaTrackingId' : IDL.Opt(IDL.Text),
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRandomUnlockState' : IDL.Func(
        [TextWorkId],
        [IDL.Opt(RandomUnlockState)],
        ['query'],
      ),
    'getRandomUnlockStatusLookup' : IDL.Func(
        [TextWorkId],
        [IDL.Bool],
        ['query'],
      ),
    'getRemovedWorksByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(WorkSummary)],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [AppSettings], ['query']),
    'getUserPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getValidWorksByCreator' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(WorkSummary)],
        ['query'],
      ),
    'getWork' : IDL.Func([TextWorkId], [IDL.Opt(Work)], ['query']),
    'getWorkDetailsWithTimeWindow' : IDL.Func([TextWorkId], [WorkDetail], []),
    'getWorkTimeWindow' : IDL.Func([TextWorkId], [TimeWindow], ['query']),
    'getWorksByCreator' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(WorkSummary)],
        ['query'],
      ),
    'getWorksForCreator' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(WorkSummary)],
        ['query'],
      ),
    'getWorksWithRandomUnlock' : IDL.Func(
        [],
        [IDL.Vec(WorkSummary)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveRandomUnlockState' : IDL.Func([TextWorkId, IDL.Text, IDL.Nat], [], []),
    'setUserPrincipal' : IDL.Func([IDL.Principal], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAnalyticsSettings' : IDL.Func(
        [
          IDL.Record({
            'analyticsEnabled' : IDL.Bool,
            'gaTrackingId' : IDL.Opt(IDL.Text),
          }),
        ],
        [],
        [],
      ),
    'updateRandomUnlockState' : IDL.Func(
        [TextWorkId, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateSettings' : IDL.Func([AppSettings], [], []),
    'updateWork' : IDL.Func(
        [
          TextWorkId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          WorkType,
          IDL.Nat,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Opt(FileVersion),
          IDL.Opt(IDL.Vec(ImageVersion)),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };