/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppSettings {
  'analyticsEnabled' : boolean,
  'gaTrackingId' : [] | [string],
  'allowAnonymousPublishing' : boolean,
}
export interface FileVersion {
  'url' : string,
  'originalFilename' : string,
  'mimeType' : string,
  'fundingThreshold' : bigint,
}
export interface ImageVersion {
  'url' : string,
  'resolutionPercentage' : bigint,
  'fundingThreshold' : bigint,
}
export interface RandomUnlockState {
  'unlockedString' : string,
  'lastUpdated' : Time,
  'fundingPercentageWhenGenerated' : bigint,
  'viewerPrincipal' : Principal,
  'workId' : TextWorkId,
}
export type TextWorkId = string;
export type Time = bigint;
export type TimeWindow = { 'permanent' : null } |
  { 'last1Hour' : null } |
  { 'last24Hours' : null } |
  { 'last7Days' : null } |
  { 'last30Days' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'principalAddress' : [] | [Principal],
  'name' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Work {
  'id' : TextWorkId,
  'workType' : WorkType,
  'fileVersion' : [] | [FileVersion],
  'title' : string,
  'creator' : Principal,
  'deleted' : boolean,
  'progressiveUnlock' : boolean,
  'content' : string,
  'accountId' : string,
  'randomUnlock' : boolean,
  'publishedAt' : Time,
  'author' : string,
  'targetAmount' : bigint,
  'imageVersions' : [] | [Array<ImageVersion>],
  'timeWindow' : TimeWindow,
}
export interface WorkDetail {
  'work' : Work,
  'unlocked' : boolean,
  'receivedAmount' : bigint,
  'unlockProgress' : bigint,
}
export interface WorkSummary {
  'id' : TextWorkId,
  'workType' : WorkType,
  'title' : string,
  'randomUnlock' : boolean,
  'publishedAt' : Time,
  'author' : string,
  'targetAmount' : bigint,
  'contentPreview' : string,
  'timeWindow' : TimeWindow,
}
export type WorkType = { 'audio' : null } |
  { 'file' : null } |
  { 'text' : null } |
  { 'image' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createWork' : ActorMethod<
    [
      TextWorkId,
      string,
      string,
      WorkType,
      bigint,
      string,
      boolean,
      boolean,
      [] | [FileVersion],
      [] | [Array<ImageVersion>],
      TimeWindow,
    ],
    undefined
  >,
  'deleteWork' : ActorMethod<[TextWorkId], undefined>,
  'getActiveWork' : ActorMethod<[TextWorkId], Work>,
  'getActiveWorksByOwner' : ActorMethod<[Principal], Array<WorkSummary>>,
  'getAllPaidWorks' : ActorMethod<[], Array<WorkSummary>>,
  'getAllWorksAdmin' : ActorMethod<[], Array<Work>>,
  'getAnalyticsSettings' : ActorMethod<
    [],
    { 'analyticsEnabled' : boolean, 'gaTrackingId' : [] | [string] }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRandomUnlockState' : ActorMethod<[TextWorkId], [] | [RandomUnlockState]>,
  'getRandomUnlockStatusLookup' : ActorMethod<[TextWorkId], boolean>,
  'getRemovedWorksByOwner' : ActorMethod<[Principal], Array<WorkSummary>>,
  'getSettings' : ActorMethod<[], AppSettings>,
  'getUserPrincipal' : ActorMethod<[], [] | [Principal]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getValidWorksByCreator' : ActorMethod<[Principal], Array<WorkSummary>>,
  'getWork' : ActorMethod<[TextWorkId], [] | [Work]>,
  'getWorkDetailsWithTimeWindow' : ActorMethod<[TextWorkId], WorkDetail>,
  'getWorkTimeWindow' : ActorMethod<[TextWorkId], TimeWindow>,
  'getWorksByCreator' : ActorMethod<[Principal], Array<WorkSummary>>,
  'getWorksForCreator' : ActorMethod<[Principal], Array<WorkSummary>>,
  'getWorksWithRandomUnlock' : ActorMethod<[], Array<WorkSummary>>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveRandomUnlockState' : ActorMethod<
    [TextWorkId, string, bigint],
    undefined
  >,
  'setUserPrincipal' : ActorMethod<[Principal], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAnalyticsSettings' : ActorMethod<
    [{ 'analyticsEnabled' : boolean, 'gaTrackingId' : [] | [string] }],
    undefined
  >,
  'updateRandomUnlockState' : ActorMethod<
    [TextWorkId, string, bigint],
    undefined
  >,
  'updateSettings' : ActorMethod<[AppSettings], undefined>,
  'updateWork' : ActorMethod<
    [
      TextWorkId,
      string,
      string,
      string,
      WorkType,
      bigint,
      string,
      boolean,
      boolean,
      [] | [FileVersion],
      [] | [Array<ImageVersion>],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];